PREFIX gn: <http://inspire.jrc.ec.europa.eu/schemas/gn/3.0/>
PREFIX au: <http://inspire.jrc.ec.europa.eu/schemas/au/3.0/>
PREFIX ps: <http://inspire.jrc.ec.europa.eu/schemas/ps/3.0/>
PREFIX geo:<http://www.opengis.net/ont/geosparql#>
SELECT ?adminName ?siteName
WHERE { 
?q au:name ?r .
?r gn:GeographicalName ?rnName .
?rnName gn:spelling ?rspn .
?rspn gn:SpellingOfName ?rspt .
?rspt gn:text ?adminName .
?q geo:hasGeometry ?qGeom .
?qGeom geo:asWKT ?qWKT .
?f ps:siteName ?p .
?p gn:GeographicalName ?gnName .
?gnName gn:spelling ?spn .
?spn gn:SpellingOfName ?spt .
?spt gn:text ?siteName .
?f geo:hasGeometry ?fGeom .
?fGeom geo:asWKT ?fWKT .
FILTER (bif:st_intersects(bif:st_get_bounding_box(?qWKT),bif:st_get_bounding_box(?fWKT)))
}
LIMIT 50

