PREFIX dc: <http://purl.org/dc/terms/>
CONSTRUCT { ?m dc:subject "Environment" .
            ?m dc:title ?k }
WHERE {
?m dc:subject "Environment" .
?m dc:title ?k .
FILTER ( REGEX( str(?k), "*network*" ) )
}
