PREFIX dc: <http://purl.org/dc/terms/>
CONSTRUCT { { ?s dc:subject "road" }    
            UNION
            { ?s dc:subject "water" } }
WHERE {
{ ?s dc:subject "road" }    
UNION
{ ?s dc:subject "water" }
}

