PREFIX gn: <http://inspire.jrc.ec.europa.eu/schemas/gn/3.0/>
PREFIX ps: <http://inspire.jrc.ec.europa.eu/schemas/ps/3.0/>
SELECT ?fName ?dist
WHERE {
?f ps:siteName ?p .
?p gn:GeographicalName ?gnName .
?gnName gn:spelling ?spn .
?spn gn:SpellingOfName ?spt .
?spt gn:text ?fName .
?f geo:hasGeometry ?fGeom .
?fGeom geo:asWKT ?fWKT .
BIND (geof:distance(?fWKT, "<http://www.opengis.net/def/crs/EPSG/0/4326> POINT (37.975598 23.735933)"^^sf:wktLiteral, units:metre) AS ?dist) .
FILTER (?dist < 20000)
}
ORDER BY ?dist

